// react-fe/src/components/ChatRoom.tsx
import { useEffect, useRef, useState, type KeyboardEvent } from 'react';
import { Send, User } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { AiAvatar } from '@/components/AiAvatar';
import { cn } from '@/lib/utils';
import type { ConnectionStatus } from '@/hooks/useSSE';

export interface Message {
  content: string;
  isUser: boolean;
  type?: string;
  time: number;
}

interface ChatRoomProps {
  messages: Message[];
  connectionStatus: ConnectionStatus;
  aiType?: 'code' | 'super' | 'default';
  onSendMessage: (message: string) => void;
}

export function ChatRoom({
  messages,
  connectionStatus,
  aiType = 'default',
  onSendMessage,
}: ChatRoomProps) {
  const [inputMessage, setInputMessage] = useState('');
  const scrollRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // 自动滚动到底部
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  // 格式化时间
  const formatTime = (timestamp: number) => {
    return new Date(timestamp).toLocaleTimeString('zh-CN', {
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // 发送消息
  const handleSend = () => {
    if (!inputMessage.trim() || connectionStatus === 'connecting') return;
    onSendMessage(inputMessage);
    setInputMessage('');
  };

  // 键盘事件
  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  // 获取消息气泡样式
  const getBubbleClass = (type?: string) => {
    switch (type) {
      case 'ai-thinking':
        return 'bg-amber-50 border-l-4 border-amber-400 italic';
      case 'ai-tool-call':
        return 'bg-gray-100 border-l-4 border-gray-400 text-sm';
      case 'ai-tool-result':
        return 'bg-sky-50 border-l-4 border-sky-400 text-sm max-h-36 overflow-y-auto';
      case 'ai-final':
        return 'bg-emerald-50 border-l-4 border-emerald-400';
      case 'ai-error':
        return 'bg-red-50 border-l-4 border-red-400';
      default:
        return 'bg-gray-100';
    }
  };

  const isConnecting = connectionStatus === 'connecting';

  return (
    <div className="flex flex-col h-[70vh] min-h-[500px] bg-white rounded-xl border border-emerald-100 shadow-sm overflow-hidden">
      {/* 消息区域 */}
      <ScrollArea className="flex-1 p-4" ref={scrollRef}>
        <div className="space-y-4">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={cn(
                'flex items-start gap-3',
                msg.isUser ? 'flex-row-reverse' : 'flex-row'
              )}
            >
              {/* 头像 */}
              {msg.isUser ? (
                <Avatar className="w-9 h-9">
                  <AvatarFallback className="bg-emerald-500 text-white">
                    <User className="w-5 h-5" />
                  </AvatarFallback>
                </Avatar>
              ) : (
                <AiAvatar type={aiType} />
              )}

              {/* 消息气泡 */}
              <div
                className={cn(
                  'max-w-[75%] px-4 py-3 rounded-2xl',
                  msg.isUser
                    ? 'bg-emerald-500 text-white rounded-br-md'
                    : cn('rounded-bl-md', getBubbleClass(msg.type))
                )}
              >
                <p className="text-sm leading-relaxed whitespace-pre-wrap break-words">
                  {msg.content}
                  {/* 打字指示器 */}
                  {!msg.isUser &&
                    isConnecting &&
                    index === messages.length - 1 && (
                      <span className="inline-block ml-1 animate-pulse">▋</span>
                    )}
                </p>
                <p
                  className={cn(
                    'text-xs mt-1.5',
                    msg.isUser ? 'text-emerald-100' : 'text-gray-400'
                  )}
                >
                  {formatTime(msg.time)}
                </p>
              </div>
            </div>
          ))}
        </div>
      </ScrollArea>

      {/* 输入区域 */}
      <div className="p-4 border-t border-emerald-50 bg-gray-50/50">
        <div className="flex items-end gap-3">
          <textarea
            ref={textareaRef}
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="输入消息..."
            disabled={isConnecting}
            className={cn(
              'flex-1 resize-none rounded-xl border border-emerald-200 px-4 py-3',
              'text-sm placeholder:text-gray-400',
              'focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-400',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'min-h-[44px] max-h-[120px]'
            )}
            rows={1}
          />
          <Button
            onClick={handleSend}
            disabled={isConnecting || !inputMessage.trim()}
            className="h-11 px-5 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl shadow-sm"
          >
            <Send className="w-4 h-4" />
          </Button>
        </div>
      </div>
    </div>
  );
}

// yu-ai-agent-frontend/src/components/ChatRoom.vue
<template>
  <div class="chat-container">
    <!-- 聊天记录区域 -->
    <div class="chat-messages" ref="messagesContainer">
      <div
        v-for="(msg, index) in messages"
        :key="index"
        class="message-wrapper"
      >
        <!-- AI消息 -->
        <div v-if="!msg.isUser" class="message ai-message" :class="[msg.type]">
          <div class="avatar ai-avatar">
            <AiAvatarFallback :type="aiType" />
          </div>
          <div class="message-bubble">
            <div class="message-content">
              {{ msg.content }}
              <span
                v-if="
                  connectionStatus === 'connecting' &&
                  index === messages.length - 1
                "
                class="typing-indicator"
                >▋</span
              >
            </div>
            <div class="message-time">{{ formatTime(msg.time) }}</div>
          </div>
        </div>

        <!-- 用户消息 -->
        <div v-else class="message user-message" :class="[msg.type]">
          <div class="message-bubble">
            <div class="message-content">{{ msg.content }}</div>
            <div class="message-time">{{ formatTime(msg.time) }}</div>
          </div>
          <div class="avatar user-avatar">
            <div class="avatar-placeholder">我</div>
          </div>
        </div>
      </div>
    </div>

    <!-- 输入区域 -->
    <div class="chat-input-container">
      <div class="chat-input">
        <textarea
          v-model="inputMessage"
          @keydown.enter.prevent="sendMessage"
          placeholder="请输入消息..."
          class="input-box"
          :disabled="connectionStatus === 'connecting'"
        ></textarea>
        <button
          @click="sendMessage"
          class="send-button"
          :disabled="connectionStatus === 'connecting' || !inputMessage.trim()"
        >
          发送
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, nextTick, watch, computed } from "vue";
import AiAvatarFallback from "./AiAvatarFallback.vue";

const props = defineProps({
  messages: {
    type: Array,
    default: () => [],
  },
  connectionStatus: {
    type: String,
    default: "disconnected",
  },
  aiType: {
    type: String,
    default: "default", // 'love' 或 'super'
  },
});

const emit = defineEmits(["send-message"]);

const inputMessage = ref("");
const messagesContainer = ref(null);

// 根据AI类型选择不同头像
const aiAvatar = computed(() => {
  return props.aiType === "love"
    ? "/ai-love-avatar.png" // 恋爱大师头像
    : "/ai-super-avatar.png"; // 超级智能体头像
});

// 发送消息
const sendMessage = () => {
  if (!inputMessage.value.trim()) return;

  emit("send-message", inputMessage.value);
  inputMessage.value = "";
};

// 格式化时间
const formatTime = (timestamp) => {
  const date = new Date(timestamp);
  return date.toLocaleTimeString("zh-CN", {
    hour: "2-digit",
    minute: "2-digit",
  });
};

// 自动滚动到底部
const scrollToBottom = async () => {
  await nextTick();
  if (messagesContainer.value) {
    messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
  }
};

// 监听消息变化与内容变化, 自动滚动
watch(
  () => props.messages.length,
  () => {
    scrollToBottom();
  },
);

watch(
  () => props.messages.map((m) => m.content).join(""),
  () => {
    scrollToBottom();
  },
);

onMounted(() => {
  scrollToBottom();
});
</script>

<style scoped>
.chat-container {
  display: flex;
  flex-direction: column;
  height: 70vh;
  min-height: 600px;
  background-color: #f5f5f5;
  border-radius: 8px;
  overflow: hidden;
  position: relative;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 16px;
  padding-bottom: 80px;
  /* 为输入框留出空间 */
  display: flex;
  flex-direction: column;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 72px;
  /* 与输入框高度相匹配 */
}

.message-wrapper {
  margin-bottom: 16px;
  display: flex;
  flex-direction: column;
  width: 100%;
}

.message {
  display: flex;
  align-items: flex-start;
  max-width: 85%;
  margin-bottom: 8px;
}

.user-message {
  margin-left: auto;
  /* 用户消息靠右 */
  flex-direction: row;
  /* 正常顺序, 先气泡后头像 */
}

.ai-message {
  margin-right: auto;
  /* AI消息靠左 */
}

.avatar {
  width: 36px;
  height: 36px;
  border-radius: 50%;
  overflow: hidden;
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: center;
}

.user-avatar {
  margin-left: 8px;
  /* 用户头像在右侧, 左边距 */
}

.ai-avatar {
  margin-right: 8px;
  /* AI头像在左侧, 右边距 */
}

.avatar-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: #007bff;
  color: white;
  font-weight: bold;
}

.message-bubble {
  padding: 12px;
  border-radius: 18px;
  position: relative;
  word-wrap: break-word;
  min-width: 100px;
  /* 最小宽度 */
}

.user-message .message-bubble {
  background-color: #007bff;
  color: white;
  border-bottom-right-radius: 4px;
  text-align: left;
}

.ai-message .message-bubble {
  background-color: #e9e9eb;
  color: #333;
  border-bottom-left-radius: 4px;
  text-align: left;
}

.message-content {
  font-size: 16px;
  line-height: 1.5;
  white-space: pre-wrap;
}

.message-time {
  font-size: 12px;
  opacity: 0.7;
  margin-top: 4px;
  text-align: right;
}

.chat-input-container {
  position: absolute;
  bottom: 0;
  left: 0;
  right: 0;
  background-color: white;
  border-top: 1px solid #e0e0e0;
  z-index: 100;
  height: 72px;
  /* 固定高度 */
  box-shadow: 0 -2px 10px rgba(0, 0, 0, 0.05);
}

.chat-input {
  display: flex;
  padding: 16px;
  height: 100%;
  box-sizing: border-box;
  align-items: center;
}

.input-box {
  flex-grow: 1;
  border: 1px solid #ddd;
  border-radius: 20px;
  padding: 10px 16px;
  font-size: 16px;
  resize: none;
  min-height: 20px;
  max-height: 40px;
  /* 限制高度 */
  outline: none;
  transition: border-color 0.3s;
  overflow-y: auto;
  scrollbar-width: none;
  /* Firefox */
  -ms-overflow-style: none;
  /* IE & Edge */
}

/* 隐藏Webkit浏览器的滚动条 */
.input-box::-webkit-scrollbar {
  display: none;
}

.input-box:focus {
  border-color: #007bff;
}

.send-button {
  margin-left: 12px;
  background-color: #007bff;
  color: white;
  border: none;
  border-radius: 20px;
  padding: 0 20px;
  font-size: 16px;
  cursor: pointer;
  transition: background-color 0.3s;
  height: 40px;
  align-self: center;
}

.send-button:hover:not(:disabled) {
  background-color: #0069d9;
}

.typing-indicator {
  display: inline-block;
  animation: blink 0.7s infinite;
  margin-left: 2px;
}

@keyframes blink {
  0% {
    opacity: 0;
  }

  50% {
    opacity: 1;
  }

  100% {
    opacity: 0;
  }
}

.input-box:disabled,
.send-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

/* 响应式设计 */
@media (max-width: 768px) {
  .message {
    max-width: 95%;
  }

  .message-content {
    font-size: 15px;
  }

  .chat-input {
    padding: 12px;
  }

  .input-box {
    padding: 8px 12px;
  }

  .send-button {
    padding: 0 15px;
    font-size: 14px;
  }
}

@media (max-width: 480px) {
  .avatar {
    width: 32px;
    height: 32px;
  }

  .message-bubble {
    padding: 10px;
  }

  .message-content {
    font-size: 14px;
  }

  .chat-input-container {
    height: 64px;
  }

  .chat-messages {
    bottom: 64px;
  }
}

/* 新增：不同类型消息的样式 */
.ai-answer {
  animation: fadeIn 0.3s ease-in-out;
}

.ai-final {
  /* 最终回答, 可以有不同的样式, 例如边框高亮等 */
}

.ai-final .message-bubble {
  background-color: #d4edda;
  border-left: 3px solid #28a745;
}

.ai-error {
  opacity: 0.7;
}

.ai-error .message-bubble {
  background-color: #f8d7da;
  border-left: 3px solid #dc3545;
}

/* 思考过程样式 */
.ai-thinking .message-bubble {
  background-color: #fff3cd;
  border-left: 3px solid #ffc107;
  font-style: italic;
}

/* 步骤标记样式 */
.ai-step .message-bubble {
  background-color: #cce5ff;
  border-left: 3px solid #007bff;
  font-size: 14px;
  padding: 8px 12px;
}

/* 工具调用样式 */
.ai-tool-call .message-bubble {
  background-color: #e2e3e5;
  border-left: 3px solid #6c757d;
  font-size: 14px;
}

/* 工具结果样式 */
.ai-tool-result .message-bubble {
  background-color: #d1ecf1;
  border-left: 3px solid #17a2b8;
  font-size: 13px;
  max-height: 150px;
  overflow-y: auto;
}

.user-question {
  /* 用户提问的特殊样式 */
}

/* 连续消息气泡样式 */
.ai-message + .ai-message {
  margin-top: 4px;
}

.ai-message + .ai-message .avatar {
  visibility: hidden;
}

.ai-message + .ai-message .message-bubble {
  border-top-left-radius: 10px;
}
</style>
