// react-fe/src/pages/SuperAgent.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Bot } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { ChatRoom, type Message } from '@/components/ChatRoom';
import { AppFooter } from '@/components/AppFooter';
import { chatWithManus } from '@/api';
import type { ConnectionStatus } from '@/hooks/useSSE';

// 结构化消息类型
interface StructuredMessage {
  type: string;
  content?: string;
  tool?: string;
  result?: string;
}

export function SuperAgent() {
  const navigate = useNavigate();
  const [messages, setMessages] = useState<Message[]>([]);
  const [connectionStatus, setConnectionStatus] = useState<ConnectionStatus>('disconnected');
  const eventSourceRef = useRef<EventSource | null>(null);

  // 添加消息
  const addMessage = useCallback(
    (content: string, isUser: boolean, type = '') => {
      setMessages((prev) => [
        ...prev,
        { content, isUser, type, time: Date.now() },
      ]);
    },
    []
  );

  // 处理结构化消息
  const handleStructuredMessage = useCallback(
    (msg: StructuredMessage) => {
      switch (msg.type) {
        case 'thinking':
          if (msg.content?.trim()) {
            addMessage(`💭 ${msg.content}`, false, 'ai-thinking');
          }
          break;
        case 'tool_call':
          addMessage(`🔧 调用工具: ${msg.tool}`, false, 'ai-tool-call');
          break;
        case 'tool_result': {
          const result =
            msg.result && msg.result.length > 200
              ? msg.result.substring(0, 200) + '...'
              : msg.result;
          addMessage(`📋 ${msg.tool} 结果: ${result}`, false, 'ai-tool-result');
          break;
        }
        case 'finished':
          addMessage(`✅ ${msg.content}`, false, 'ai-final');
          break;
        case 'error':
          addMessage(`❌ ${msg.content}`, false, 'ai-error');
          break;
        default:
          if (msg.content) {
            addMessage(msg.content, false);
          }
      }
    },
    [addMessage]
  );

  // 发送消息
  const handleSendMessage = useCallback(
    (message: string) => {
      // 添加用户消息
      addMessage(message, true, 'user-question');

      // 关闭之前的连接
      if (eventSourceRef.current) {
        eventSourceRef.current.close();
      }

      // 建立 SSE 连接
      setConnectionStatus('connecting');
      const eventSource = chatWithManus(message);
      eventSourceRef.current = eventSource;

      // 消息缓冲
      let messageBuffer: string[] = [];
      const chineseEndPunctuation = ['。', '！', '？', '…'];

      // 创建消息气泡
      const createBubble = (content: string, type = 'ai-answer') => {
        if (content.trim()) {
          addMessage(content, false, type);
        }
        messageBuffer = [];
      };

      eventSource.onmessage = (event) => {
        const data = event.data;

        if (data && data !== '[DONE]') {
          try {
            // 尝试解析 JSON 格式
            const parsed = JSON.parse(data) as StructuredMessage;
            handleStructuredMessage(parsed);
          } catch {
            // 兼容纯文本消息
            messageBuffer.push(data);
            const combinedText = messageBuffer.join('');
            const lastChar = data.charAt(data.length - 1);
            const hasCompleteSentence =
              chineseEndPunctuation.includes(lastChar) || data.includes('\n\n');
            const isLongEnough = combinedText.length > 40;

            if (hasCompleteSentence || isLongEnough) {
              createBubble(combinedText);
            }
          }
        }

        if (data === '[DONE]') {
          // 处理剩余内容
          if (messageBuffer.length > 0) {
            createBubble(messageBuffer.join(''), 'ai-final');
          }
          setConnectionStatus('disconnected');
          eventSource.close();
        }
      };

      eventSource.onerror = () => {
        if (messageBuffer.length > 0) {
          createBubble(messageBuffer.join(''), 'ai-error');
        }
        setConnectionStatus('error');
        eventSource.close();
      };
    },
    [addMessage, handleStructuredMessage]
  );

  // 初始化欢迎消息
  useEffect(() => {
    addMessage(
      '你好，我是 AI 超级智能体！我可以解答各类问题，提供专业建议，请问有什么可以帮助你的吗？',
      false
    );

    return () => {
      if (eventSourceRef.current) {
        eventSourceRef.current.close();
      }
    };
  }, [addMessage]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50/50 to-white flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-20 bg-white/80 backdrop-blur-md border-b border-blue-100">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/')}
            className="text-gray-600 hover:text-blue-600"
          >
            <ArrowLeft className="w-4 h-4 mr-1" />
            返回
          </Button>

          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-400 to-indigo-500 flex items-center justify-center">
              <Bot className="w-4 h-4 text-white" />
            </div>
            <h1 className="font-semibold text-gray-800">AI 超级智能体</h1>
          </div>

          <div className="w-16" />
        </div>
      </header>

      {/* 主内容 */}
      <main className="flex-1 max-w-4xl w-full mx-auto px-4 py-6">
        <ChatRoom
          messages={messages}
          connectionStatus={connectionStatus}
          aiType="super"
          onSendMessage={handleSendMessage}
        />
      </main>

      {/* Footer */}
      <AppFooter />
    </div>
  );
}

// yu-ai-agent-frontend/src/views/SuperAgent.vue
<template>
  <div class="super-agent-container">
    <div class="header">
      <div class="back-button" @click="goBack">返回</div>
      <h1 class="title">AI超级智能体</h1>
      <div class="placeholder"></div>
    </div>

    <div class="content-wrapper">
      <div class="chat-area">
        <ChatRoom
          :messages="messages"
          :connection-status="connectionStatus"
          ai-type="super"
          @send-message="sendMessage"
        />
      </div>
    </div>

    <div class="footer-container">
      <AppFooter />
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";
import { useRouter } from "vue-router";
import { useHead } from "@vueuse/head";
import ChatRoom from "../components/ChatRoom.vue";
import AppFooter from "../components/AppFooter.vue";
import { chatWithManus } from "../api";

// 设置页面标题和元数据
useHead({
  title: "AI超级智能体 - 鱼皮AI超级智能体应用平台",
  meta: [
    {
      name: "description",
      content:
        "AI超级智能体是鱼皮AI超级智能体应用平台的全能助手, 能解答各类专业问题, 提供精准建议和解决方案",
    },
    {
      name: "keywords",
      content: "AI超级智能体,智能助手,专业问答,AI问答,专业建议,鱼皮,AI智能体",
    },
  ],
});

const router = useRouter();
const messages = ref([]);
const connectionStatus = ref("disconnected");
let eventSource = null;

// 添加消息到列表
const addMessage = (content, isUser, type = "") => {
  messages.value.push({
    content,
    isUser,
    type,
    time: new Date().getTime(),
  });
};

// 发送消息
const sendMessage = (message) => {
  addMessage(message, true, "user-question");

  // 连接SSE
  if (eventSource) {
    eventSource.close();
  }

  // 设置连接状态
  connectionStatus.value = "connecting";

  // 临时存储
  let messageBuffer = []; // 用于存储SSE消息的缓冲区
  let lastBubbleTime = Date.now(); // 上一个气泡的创建时间
  let isFirstResponse = true; // 是否是第一次响应

  const chineseEndPunctuation = ["; ", "!", "?", "…"]; // 中文句子结束标点
  const minBubbleInterval = 800; // 气泡最小间隔时间(毫秒)

  // 创建消息气泡的函数
  const createBubble = (content, type = "ai-answer") => {
    if (!content.trim()) return;

    // 添加适当的延迟, 使消息显示更自然
    const now = Date.now();
    const timeSinceLastBubble = now - lastBubbleTime;

    if (isFirstResponse) {
      // 第一条消息立即显示
      addMessage(content, false, type);
      isFirstResponse = false;
    } else if (timeSinceLastBubble < minBubbleInterval) {
      // 如果与上一气泡间隔太短, 添加一个延迟
      setTimeout(() => {
        addMessage(content, false, type);
      }, minBubbleInterval - timeSinceLastBubble);
    } else {
      // 正常添加消息
      addMessage(content, false, type);
    }

    lastBubbleTime = now;
    messageBuffer = []; // 清空缓冲区
  };

  eventSource = chatWithManus(message);

  // 监听SSE消息
  eventSource.onmessage = (event) => {
    const data = event.data;

    if (data && data !== "[DONE]") {
      // 尝试解析 JSON 格式的消息
      try {
        const parsed = JSON.parse(data);
        handleStructuredMessage(parsed);
      } catch {
        // 兼容旧格式的纯文本消息
        messageBuffer.push(data);

        // 检查是否应该创建新气泡
        const combinedText = messageBuffer.join("");

        // 句子结束或消息长度达到阈值
        const lastChar = data.charAt(data.length - 1);
        const hasCompleteSentence =
          chineseEndPunctuation.includes(lastChar) || data.includes("\n\n");
        const isLongEnough = combinedText.length > 40;

        if (hasCompleteSentence || isLongEnough) {
          createBubble(combinedText);
        }
      }
    }

    if (data === "[DONE]") {
      // 如果还有未显示的内容, 创建最后一个气泡
      if (messageBuffer.length > 0) {
        const remainingContent = messageBuffer.join("");
        createBubble(remainingContent, "ai-final");
      }

      // 完成后关闭连接
      connectionStatus.value = "disconnected";
      eventSource.close();
    }
  };

  // 处理结构化消息
  const handleStructuredMessage = (msg) => {
    switch (msg.type) {
      case "step_start":
        // 步骤开始 - 不显示步骤信息
        break;
      case "thinking":
        // AI 思考内容
        if (msg.content?.trim()) {
          createBubble(`💭 ${msg.content}`, "ai-thinking");
        }
        break;
      case "tool_call":
        // 工具调用
        createBubble(`🔧 调用工具: ${msg.tool}`, "ai-tool-call");
        break;
      case "tool_result":
        // 工具结果 (截取前200字符)
        const result =
          msg.result?.length > 200
            ? msg.result.substring(0, 200) + "..."
            : msg.result;
        createBubble(`📋 ${msg.tool} 结果: ${result}`, "ai-tool-result");
        break;
      case "step_result":
        // 步骤结果 (可选显示)
        break;
      case "finished":
        createBubble(`✅ ${msg.content}`, "ai-final");
        break;
      case "error":
        createBubble(`❌ ${msg.content}`, "ai-error");
        break;
      default:
        // 未知类型, 显示原始内容
        if (msg.content) {
          createBubble(msg.content);
        }
    }
  };

  // 监听SSE错误
  eventSource.onerror = (error) => {
    console.error("SSE Error:", error);
    connectionStatus.value = "error";
    eventSource.close();

    // 如果出错时有未显示的内容, 也创建气泡
    if (messageBuffer.length > 0) {
      const remainingContent = messageBuffer.join("");
      createBubble(remainingContent, "ai-error");
    }
  };
};

// 返回主页
const goBack = () => {
  router.push("/");
};

// 页面加载时添加欢迎消息
onMounted(() => {
  // 添加欢迎消息
  addMessage(
    "你好, 我是AI超级智能体; 我可以解答各类问题, 提供专业建议, 请问有什么可以帮助你的吗?",
    false,
  );
});

// 组件销毁前关闭SSE连接
onBeforeUnmount(() => {
  if (eventSource) {
    eventSource.close();
  }
});
</script>

<style scoped>
.super-agent-container {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  background-color: #f9fbff;
}

.header {
  display: grid;
  grid-template-columns: 1fr auto 1fr;
  align-items: center;
  padding: 16px 24px;
  background-color: #3f51b5;
  color: white;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 10;
}

.back-button {
  font-size: 16px;
  cursor: pointer;
  display: flex;
  align-items: center;
  transition: opacity 0.2s;
  justify-self: start;
}

.back-button:hover {
  opacity: 0.8;
}

.back-button:before {
  content: "←";
  margin-right: 8px;
}

.title {
  font-size: 20px;
  font-weight: bold;
  margin: 0;
  text-align: center;
  justify-self: center;
}

.placeholder {
  width: 1px;
  justify-self: end;
}

.content-wrapper {
  display: flex;
  flex-direction: column;
  flex: 1;
}

.chat-area {
  flex: 1;
  padding: 16px;
  overflow: hidden;
  position: relative;
  /* 设置最小高度确保内容显示正常 */
  min-height: calc(100vh - 56px - 180px);
  /* 100vh减去头部高度和页脚高度 */
  margin-bottom: 16px;
  /* 为页脚留出空间 */
}

.footer-container {
  margin-top: auto;
}

/* 响应式样式 */
@media (max-width: 768px) {
  .header {
    padding: 12px 16px;
  }

  .title {
    font-size: 18px;
  }

  .chat-area {
    padding: 12px;
    min-height: calc(100vh - 48px - 160px);
    /* 调整计算值 */
    margin-bottom: 12px;
  }
}

@media (max-width: 480px) {
  .header {
    padding: 10px 12px;
  }

  .back-button {
    font-size: 14px;
  }

  .title {
    font-size: 16px;
  }

  .chat-area {
    padding: 8px;
    min-height: calc(100vh - 42px - 150px);
    /* 再次调整计算值 */
    margin-bottom: 8px;
  }
}
</style>
